services:
  conntrack-monitor:
    image: ghcr.io/0xf00f00/conntrack-monitor:latest
    container_name: conntrack-monitor

    cap_add:
      - NET_ADMIN

    privileged: true
    tty: true
    stdin_open: true

    network_mode: host

    volumes:
      - geoip-data:/usr/share/GeoIP

    environment:
      - GEOIP_DB_PATHS=/usr/share/GeoIP

    restart: unless-stopped

volumes:
  geoip-data:
    driver: local
